Force-check all configs with latest capabilities
Hack the qemuxml2argvtest to force-validate everything with latest
capabilities. The result is expected:

190) QEMU XML-2-ARGV disk-network-tlsx509-vxhs.x86_64-5.0.0            ... failed to validate -blockdev '{"driver":"vxhs","tls-creds":"objlibvirt-3-storage_tls0","vdisk-id":"eb90327c-8302-4725-9e1b-4e85ed4dc251","server":{"host":"192.168.0.1","port":"9999"},"node-name":"libvirt-3-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"}' against QAPI schema: {
   ERROR: variant 'vxhs' for discriminator 'driver' not found

FAILED
1036) QEMU XML-2-ARGV launch-security-sev.x86_64-2.12.0                 ... failed to validate -object '{"qom-type":"sev-guest","id":"sev0","cbitpos":47,"reduced-phys-bits":1,"policy":1,"dh-cert-file":"/tmp/lib/domain--1-QEMUGuest1/dh_cert.base64","session-file":"/tmp/lib/domain--1-QEMUGuest1/session.base64"}' against QAPI schema: {
   ERROR: variant 'sev-guest' for discriminator 'qom-type' not found

FAILED
1037) QEMU XML-2-ARGV launch-security-sev-missing-platform-info.x86_64-2.12.0 ... failed to validate -object '{"qom-type":"sev-guest","id":"sev0","cbitpos":47,"reduced-phys-bits":1,"policy":1,"dh-cert-file":"/tmp/lib/domain--1-QEMUGuest1/dh_cert.base64","session-file":"/tmp/lib/domain--1-QEMUGuest1/session.base64"}' against QAPI schema: {
   ERROR: variant 'sev-guest' for discriminator 'qom-type' not found

FAILED

'vxhs' was deprecated/removed and is also not an '-object' and
'sev-guest' was not enabled on the box I used for generating the
capabilities.
Message-Id: <c02ca5a9b3902482dedad14bb67aa78edcbae83e.1614182040.git.pkrempa@redhat.com>