storage_backend_rbd: Ignore rbd_diff_iterate error() if needed
When cloning an RBD volume we try to find a snapshot which is
not different to the image we're trying to clone. This boils down
to calling rbd_diff_iterate() or rbd_diff_iterate2() on systems
with newer ceph. These two are passed a callback -
virStorageBackendRBDIterateCb() which sets @diff to 1 and returns
-1. The idea is to stop iterating as soon as possible (i.e. we're
iterating over a snapshot with some deltas). Unfortunately,
returning a negative value from the callback means that iterate()
function fails and thus we report an error:

  virsh # vol-clone --pool rbd_image_root coreos_2023 coreos00.disk
  error: Failed to clone vol from coreos_2023
  error: failed to iterate RBD snapshot coreos_2023@base: Operation not
  permitted

Therefore, report an error if and only if it doesn't originates
in the callback.

Reported on libvirt-users list:

https://www.redhat.com/archives/libvirt-users/2019-April/msg00060.html

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>
Message-Id: <4a9a9154e7f07322731ef62254aa3b811fce42d9.1556548704.git.mprivozn@redhat.com>
Reviewed-by: Ján Tomko <jtomko@redhat.com>