qemu: Don't use asyncJob after stop during snapshot revert
Attempting to use the FORCE flag for snapshot-revert was resulting
in failures because qemuProcessStart and qemuProcessStartCPUs were
using QEMU_ASYNC_JOB_START after a qemuProcessStop resulting in an
error when entering the monitor:

error: internal error: unexpected async job 6 type expected 0

So create a local @jobType, initialize to QEMU_ASYNC_JOB_START, and
change to QEMU_ASYNC_JOB_NONE if we end up in the --force path
where the qemuProcessStop is run before a Start and StartCPUs.

https://bugzilla.redhat.com/show_bug.cgi?id=1591628

Signed-off-by: John Ferlan <jferlan@redhat.com>
Message-Id: <20180619225419.32039-6-jferlan@redhat.com>