util: Cast to 'long double' when calling isnan()
Clang 3.9 chokes when calling isnan() on a double variable:

  util/virxml.c:153:21: error: implicit conversion increases
                        floating-point precision: 'double' to
                        'long double' [-Werror,-Wdouble-promotion]
          (isnan(obj->floatval))) {
           ~~~~~~~~~~~^~~~~~~~~
  /usr/include/math.h:360:46: note: expanded from macro 'isnan'
  #  define isnan(x) __MATH_TG ((x), __isnan, (x))
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
  /usr/include/math.h:295:16: note: expanded from macro '__MATH_TG'
     : FUNC ## l ARGS)
       ~~~~~~~~~ ^~~~

Note how the wrong version of isnan() is being called: isnanl()
is for 'long double's, but obj->floatval is a double and a
suitable version should be called instead.

Cast the value to 'long double' to make the compiler happy.
Message-Id: <1483380931-1217-3-git-send-email-abologna@redhat.com>