spec: Add the man pages of split daemons
Fix the errors from commit a7cafa7bc2 when build RPMs from spec file:
error: Installed (but unpackaged) file(s) found:
   /usr/share/man/man8/virtinterfaced.8.gz
   /usr/share/man/man8/virtlxcd.8.gz
   /usr/share/man/man8/virtnetworkd.8.gz
   /usr/share/man/man8/virtnodedevd.8.gz
   /usr/share/man/man8/virtnwfilterd.8.gz
   /usr/share/man/man8/virtproxyd.8.gz
   /usr/share/man/man8/virtqemud.8.gz
   /usr/share/man/man8/virtsecretd.8.gz
   /usr/share/man/man8/virtstoraged.8.gz
   /usr/share/man/man8/virtvboxd.8.gz
   /usr/share/man/man8/virtxend.8.gz

Signed-off-by: Han Han <hhan@redhat.com>
Message-Id: <20210116065609.71571-1-hhan@redhat.com>