qemu: report a nicer error when USB is disabled
If the user tries to define a domain that has

  <controller type='usb' model='none'/>

and also some USB devices, we report an error:
  error: internal error: No free USB ports

Which is technically still correct for a domain with no USB ports.

Change it to:

USB is disabled for this domain, but USB devices are present in the domain XML

https://bugzilla.redhat.com/show_bug.cgi?id=1347550
Message-Id: <7e43f51ada6c1ea13a1a9de8db9670250e4eaf9c.1505917117.git.jtomko@redhat.com>
Reviewed-by: Andrea Bolognani <abologna@redhat.com>