apparmor: pass attach_disconnected
to cure

 + virsh lxc-enter-namespace --noseclabel <container> <cmd>
 libvirt:  error : Expected at least one file descriptor
 error: internal error: Child process (2714) unexpected exit status 125

caused by

 apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/libvirtd" name="" pid=1422 comm="libvirtd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Message-Id: <20161219072136.4jbhcs5eoqmddrpu@bogon.m.sigxcpu.org>