virFirewallAddRule: fix build with clang
clang complains:
util/virfirewall.c:425:20: error: passing an object that undergoes
default argument promotion to 'va_start' has undefined behavior
[-Werror,-Wvarargs]
    __builtin_va_start(args, layer);

Introduce a macro wrapper that puts a NULL pointer after the enum
argument.
Message-Id: <c67d4ca1d9fe785b3c6bc4e99322faadc3095b45.1481284688.git.jtomko@redhat.com>