libxl: relax checks on <emulator>
Checking for the existence and execute permission of a user-specified
emulator is fine when actually creating a VM, but is problematic when
running unit tests since a development system may not have the
emulator installed.

Defer the emulator checks to libxl, when actually starting a VM. One
downside is errors associated with non-existent or non-executable
emulator are reported in the libxl driver log files instead of being
returned through the libvirt API. E.g. before this change

virsh create test.xml
error: Failed to create domain from test.xml
error: unsupported configuration: emulator '/foo/bar' not found

After this change

virsh create test.xml
error: Failed to create domain from test.xml
error: internal error: libxenlight failed to create new domain 'test'

but the libxl driver log file contains

2017-02-23 22:04:18.319+0000: libxl: libxl_dm.c:2050:libxl__spawn_local_dm:
device model /foo/bar is not executable: No such file or directory

Signed-off-by: Jim Fehlig <jfehlig@suse.com>
Message-Id: <20170227020227.15438-3-jfehlig@suse.com>