m4: Work around MinGW detection of strncpy() usage
With the recent update in Fedora Rawhide, MinGW has
started freaking out about our use of strncpy():

    In function 'virStrncpy',
      inlined from 'virStrcpy' at ../../src/util/virstring.c:811:12:
  ../../src/util/virstring.c:789:11: error: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
       ret = strncpy(dest, src, n);
             ^~~~~~~~~~~~~~~~~~~~~
  ../../src/util/virstring.c: In function 'virStrcpy':
  ../../src/util/virstring.c:811:12: note: length computed here
       return virStrncpy(dest, src, strlen(src), destbytes);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

What the compiler is not detecting is that we perform
proper bound checking right before calling the function,
which makes our use of it perfectly safe.

Signed-off-by: Andrea Bolognani <abologna@redhat.com>
Message-Id: <20180717110957.12036-4-abologna@redhat.com>