error: Add VIR_ERR_DEPRECATED error code
Allow a simple programatic check that a given feature is no longer
supported by introducing a separate error code for this scenario.

Signed-off-by: Peter Krempa <pkrempa@redhat.com>
Message-Id: <6699b7cc59565b5671f3e870d12a15f918c69c65.1561098810.git.pkrempa@redhat.com>
Reviewed-by: Ján Tomko <jtomko@redhat.com>