security: Avoid calling virSecurityManagerCheckModel with NULL model
Attempting to create a domain with <seclabel type='none'/> results in

virsh --connect lxc:/// create distro_nosec.xml
error: Failed to create domain from distro_nosec.xml
error: unsupported configuration: Security driver model '(null)' is not available

With <seclabel type='none'/>, the model field of virSecurityLabelDef will
be NULL, causing virSecurityManagerCheckModel() to fail with the above
error. Avoid calling virSecurityManagerCheckModel() when they seclabel
type is VIR_DOMAIN_SECLABEL_NONE.

Signed-off-by: Jim Fehlig <jfehlig@suse.com>
Message-Id: <20201203025715.31994-3-jfehlig@suse.com>