meson: tools: depend on keycode generated sources
Tools depend on keycode generated sources, so declare that as an
explicit dependency, otherwise it might fail with:

../tools/virsh-completer-domain.c:35:10: fatal error: 'virkeynametable_linux.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Roman Bogorodskiy <bogorodskiy@gmail.com>
Message-Id: <20210303041205.98159-1-bogorodskiy@gmail.com>
Reviewed-by: Ján Tomko <jtomko@redhat.com>