cpu_conf: Fix XPath for parsing TSC frequency
Due to this bug the following command would fail on any host where TSC
frequency can be probed:

    $ virsh capabilities | virsh cpu-baseline /dev/stdin
    error: unsupported configuration: Invalid TSC frequency

https://bugzilla.redhat.com/show_bug.cgi?id=1641702

Signed-off-by: Jiri Denemark <jdenemar@redhat.com>
Message-Id: <3ea90614a378f58638a74c785fbb0c033d512072.1559806382.git.jdenemar@redhat.com>
Reviewed-by: Ján Tomko <jtomko@redhat.com>