vierror: Define VIR_ERROR_MAX_LENGTH macro
And use it instead of a magic 1024 constant.

Signed-off-by: Jiri Denemark <jdenemar@redhat.com>
Message-Id: <f4dd89418adef8d18523929ab3a175a46cb9fc22.1511354114.git.jdenemar@redhat.com>
Reviewed-by: Pavel Hrdina <phrdina@redhat.com>