lxc: Fix 'domblkstat' error with attached disk devices.
LXC was not working when you attached a new disk that points to block
device. See: https://bugzilla.redhat.com/show_bug.cgi?id=1697115.
Command line from virsh was showing problems with alias first (this
feature is not supported) and after, problems to query block device. It
was happening because extra disks were not being included into
cgroup blkio.throttle properties and libvirt could not query this info.
Applying those devices into 'allowed' list is not enough, libvirt should
reset blkio.throttle as a workaround to include disks into container's
cgroup directory.

Before:

    virsh # domblkstat CentOS hda
    error: Failed to get block stats for domain 'CentOS' device 'hda'
    error: internal error: domain stats query failed

Now:

    virsh # domblkstat CentOS hda
    hda rd_req 0
    hda rd_bytes 0
    hda wr_req 0
    hda wr_bytes 0

Signed-off-by: Julio Faracco <jcfaracco@gmail.com>
Message-Id: <20191021035436.14063-1-jcfaracco@gmail.com>