qemu: migration: remove unused variable
../src/qemu/qemu_migration.c:4091:36: error: unused variable 'cfg' [-Werror,-Wunused-variable]
    g_autoptr(virQEMUDriverConfig) cfg = virQEMUDriverGetConfig(driver);

Signed-off-by: Ján Tomko <jtomko@redhat.com>
Fixes: d92c2bbc6597fcb951b303a9122ec1ca71514d10
Message-Id: <7afc99ae2daf8b50021c94ec40c5cd71b5c2b79c.1599469562.git.jtomko@redhat.com>