qemu: hotplug: fail when net device detach times out
qemuDomainDetachNetDevice should not treat a timeout in a call to
qemuDomainWaitForDeviceRemoval as success. Instead, it should treat it
as failure -- this is the intention behind having a timeout.

If qemuDomainWaitForDeviceRemoval times out, it returns 0. In this
instance, if qemuDomainDetachNetDevice returns 0, virsh detach-interface
reports:

  Interface detached successfully

with a zero exit status.

But with a negative return value from qemuDomainDetachNetDevice, virsh
detach-interface reports:

  error: Failed to detach interface
  error: An error occurred, but the cause is unknown

with a non-zero exit status, which is more appropriate.

Signed-off-by: Jonathan Davies <jonathan.davies@nutanix.com>
Message-Id: <20180313140708.13855-1-jonathan.davies@nutanix.com>