qemu_domain.c: do not launch ppc64 guests with 'pvspinlock' setting
PowerPC does not support the 'pvspinlock' feature. The "<pvspinlock/>"
declaration will always have a value 'on' or 'off', and both will
break QEMU when launching. This is the error message for
"<pvspinlock state='on'/>":

qemu-kvm: Expected key=value format, found +kvm_pv_unhalt

A similar error message is thrown for "<pvspinlock state='off'/>".

This patch prevents the pseries guest from launching with any
pvspinlock setting with a more informative error message:

error: unsupported configuration: The 'pvspinlock' feature is not
supported for architecture 'ppc64' or machine type 'pseries'

Signed-off-by: Daniel Henrique Barboza <danielhb413@gmail.com>
Message-Id: <20200319214407.714006-3-danielhb413@gmail.com>