qemu: Add default address type for vhost-user interface on aarch64
on aarch64, hotadd vhost-user interface with the follow xml file:
<interface type='vhostuser'>
  <mac address='fa:16:3e:a2:e1:58'/>
  <source type='unix' path='/var/run/vhu24a3f044-80' mode='server'/>
  <target dev='vhu24a3f044-80'/>
  <model type='virtio'/>
</interface>

will get error like that:
error: internal error: Nicdev support unavailable

Because there is no device address type specified in xml file, so
qemuDomainSupportsNicdev returns 'false' when invoked in
qemuDomainAttachNetDevice. Using pci as the default address type,
and assigns pci address later in qemuDomainEnsurePCIAddress.

Signed-off-by: Wang Yechao <wang.yechao255@zte.com.cn>
Message-Id: <1544779172-5512-1-git-send-email-wang.yechao255@zte.com.cn>