conf: split out virDomainFeaturesDefParse
The virDomainDefParseXML function has grown so large it broke the build:
../../src/conf/domain_conf.c:20362:1: error: stack frame size of 4168 bytes
in function 'virDomainDefParseXML' [-Werror,-Wframe-larger-than=]

Signed-off-by: Ján Tomko <jtomko@redhat.com>
Message-Id: <481d52c2109ae53f8d5615836641c969b103909f.1587488347.git.jtomko@redhat.com>
Reviewed-by: Peter Krempa <pkrempa@redhat.com>