APPLY ONLY FOR TESTING PURPOSES
Modify GetAllStats to generate a long enough pause in order to send a
SIGTERM to libvirtd while a client connection is processing.

In order to "set things up":

1. In one terminal window from a local branch built using these
   patches using a root account run libvirtd debug, e.g.:

    # ./run gdb daemon/libvirtd

    once running, type a 'c' (e.g. continue) and <return>

2. Start a domain (or have one running with the current libvirtd)

    virsh start $domain

3. Prepare a domstats command for that domain (but don't yet
   hit <return> in order run it):

    virsh domstats $domain

4. Prepare a kill command for the running libvirtd, e.g.:

jferlan   4143  4107  0 09:51 pts/1    00:00:00 vim +1396 daemon/libvirtd.c
root     30054 21195  6 11:17 pts/8    00:00:01 gdb /home/jferlan/git/libvirt.work/daemon/.libs/lt-libvirtd
root     30087 30054  7 11:17 pts/8    00:00:01 /home/jferlan/git/libvirt.work/daemon/.libs/lt-libvirtd
root     30385 19861  0 11:17 pts/17   00:00:00 grep --color=auto libvirtd

    but again don't hit <return> yet.

5. Align your stars perfectly now...

   a. Hit <return> on your domstats command
   b. Swap to the kill command window and hit <return>

   This should cause the libvirtd debug window to stop, but since you
   already typed 'c' it'll continue at least briefly, for example:

...
[Thread 0x7fffc3231700 (LWP 30374) exited]
Detaching after fork from child process 30376.
Detaching after fork from child process 30377.
Detaching after fork from child process 30378.
[Thread 0x7fffc4445700 (LWP 30106) exited]
c
2018-01-10 16:18:12.962+0000: 30094: info : libvirt version: 4.0.0
2018-01-10 16:18:12.962+0000: 30094: info : hostname: unknown4ceb42c824f4.attlocal.net
2018-01-10 16:18:12.962+0000: 30094: warning : qemuConnectGetAllDomainStats:20265 : k = -5340232226128654848

Thread 1 "lt-libvirtd" received signal SIGTERM, Terminated.
0x00007ffff3ae6d2d in poll () from /lib64/libc.so.6
...
(gdb) c
Continuing.
[Thread 0x7fffc5c48700 (LWP 30103) exited]
[Thread 0x7fffc5447700 (LWP 30104) exited]
[Thread 0x7fffc4c46700 (LWP 30105) exited]
[Thread 0x7fffc6449700 (LWP 30102) exited]
[Thread 0x7fffc6c4a700 (LWP 30101) exited]
[Thread 0x7fffe3b57700 (LWP 30097) exited]
[Thread 0x7fffe4358700 (LWP 30096) exited]
[Thread 0x7fffe2354700 (LWP 30100) exited]
[Thread 0x7fffe3356700 (LWP 30098) exited]
[Thread 0x7fffe2b55700 (LWP 30099) exited]
[Thread 0x7fffe535a700 (LWP 30094) exited]
[Thread 0x7fffe5b5b700 (LWP 30093) exited]
[Thread 0x7fffe635c700 (LWP 30092) exited]
[Thread 0x7fffe6b5d700 (LWP 30091) exited]
2018-01-10 16:18:25.451+0000: 30095: warning : qemuConnectGetAllDomainStats:20265 : k = -5340232226128654848
[Thread 0x7fffe4b59700 (LWP 30095) exited]
[Thread 0x7fffc3a32700 (LWP 30187) exited]
[Inferior 1 (process 30087) exited normally]
(gdb) c
The program is not being run.
(gdb) quit

    The virsh domstats window will "close" as follows:

error: Disconnected from qemu:///system due to end of file
error: End of file while reading data: Input/output error

If something's wrong, then the libvirtd window may not exit those
final two threads in which case you could interrupt it (^c) and
check the threads (thread apply all bt) which will probably show
some sort of hang... My testing shows that the hang no longer
occurs with all the previous patches applied.

The subsequent patch calling virHashRemoveAll from virNetDaemonClose
does not seem to be necessary, although I suppose it cannot hurt as
the same essential functionality occurs during the Dispose function

Signed-off-by: John Ferlan <jferlan@redhat.com>
Message-Id: <20180119172311.15525-10-jferlan@redhat.com>