tools: console: Relax stream EOF handling
Regular VM shutdown triggers the error for existing session of virsh
console and it returns with non-zero exit code:
  error: internal error: console stream EOF

The message and status code are misleading because there's no real
error. virStreamRecv returns 0 when the end of the stream is reached.
In that case, virStreamFinish should be used to get confirmation of
stream completion. virSteramAbort is used otherwise to terminate the
stream early before an EOF.

Fixes: 29f2b5248c6 ("tools: console: pass stream/fd errors to user")
Signed-off-by: Roman Bolshakov <r.bolshakov@yadro.com>
Message-Id: <20190812111556.50439-1-r.bolshakov@yadro.com>