qemu: fix vcpupin fail as no vcpu tid set
vcpupin will fail when maxvcpus is larger than current
vcpu:

virsh vcpupin win7 --vcpu 0 --cpulist 5-6
error: Requested operation is not valid: cpu affinity is not supported

win7 xml in the command above is like below:
...
<vcpu current="3" placement="static">8</vcpu>
...

This issue is caused by qemuDomainRefreshVcpuInfo(), which mistake to
make validTIDs false and not set vcpu tid because vcpu[3] and vcpu[4]
have duplicate zero tids.

This patch fix this.

Signed-off-by: Yi Wang <wang.yi59@zte.com.cn>
Message-Id: <1550481691-34046-1-git-send-email-wen.yang99@zte.com.cn>