qemuDomainPostParseDataAlloc: Don't reset error if looking up caps fails
When starting the QEMU driver we load all domain XMLs. This
means, that post parse callbacks are run for each XML, but they
are allowed to fail because we will run them again when starting
a domain. In the case I am fixing, we were unable to look up QEMU
capabilities (in both post parse runs) and reported appropriate
error, sort of. It can be found in the logs, but the caller
doesn't get it because after 5331c4804f4 it is reset. Therefore,
as reported here [1], if we are unable to start QEMU for caps
probing the following will happen:

  virsh start fedora
  error: Failed to start domain fedora
  error: An error occurred, but the cause is unknown

1: https://www.redhat.com/archives/libvir-list/2020-July/msg00673.html

Fixes: 5331c4804f4

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>
Message-Id: <cec1794b91d19e5ea0d8c5217f9a7746bf3377d7.1594970874.git.mprivozn@redhat.com>