maint: Avoid -Ignulib on standalone examples
Travis shows that clang (but not gcc) fails to build after our
recent gnulib updates, due to:

  CC       domtop/domtop.o
In file included from dommigrate/dommigrate.c:26:
In file included from ../gnulib/lib/stdlib.h:100:
In file included from ../gnulib/lib/unistd.h:40:
In file included from /usr/include/unistd.h:638:
In file included from ../gnulib/lib/sys/select.h:110:
In file included from ../gnulib/lib/signal.h:67:
../gnulib/lib/pthread.h:74:3: error: "Please include config.h first."
 #error "Please include config.h first."

This probably stems from gcc and clang having a subtle difference in
-isystem vs. -I include behaviors on #include_next, where that difference
then results in clang trying to pick up same-named gnulib headers merely
because their directory was in the search path, while gcc did not hit
that problem.

But for our examples that are intended to be standalone, we want to
work with the bare-bones libc, without any interference from our
<config.h> or from gnulib.  The easiest way to do that is by using
per-binary CPPFLAGS, and including gnulib headers only for example
binaries that still use <config.h>.

Signed-off-by: Eric Blake <eblake@redhat.com>

Message-Id: <20190104201220.13519-4-eblake@redhat.com>