tests: Fix mode_t usage with va_arg()
Clang complains about it:

  virfilewrapper.c:270:27: error: second argument to 'va_arg'
    is of promotable type 'mode_t' (aka 'unsigned short'); this
    va_arg has undefined behavior because arguments will be
    promoted to 'int' [-Werror,-Wvarargs]

  mode = va_arg(ap, mode_t);
                    ^~~~~~

The issue was raised[1] when the patch was posted, but apparently
not acted upon. Implement the suggested fix.

[1] https://www.redhat.com/archives/libvir-list/2017-October/msg00127.html

Signed-off-by: Andrea Bolognani <abologna@redhat.com>
Message-Id: <20180430165303.6124-8-abologna@redhat.com>